framework:
    cache:
        app: cache.adapter.redis_tag_aware
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            cache.api_collections:
                adapter: cache.adapter.redis_tag_aware
                default_lifetime: 300

            cache.translations:
                adapter: cache.adapter.redis_tag_aware
                default_lifetime: 86400

            cache.catalog:
                adapter: cache.adapter.redis_tag_aware
                default_lifetime: 300

            cache.pricing:
                adapter: cache.adapter.redis_tag_aware
                default_lifetime: 300
