<?php

declare(strict_types=1);

namespace App\Payment\Domain\ValueObject;

/**
 * Transaction ID Value Object.
 *
 * Wrapper for payment gateway transaction identifiers (e.g., Stripe charge ID, PayPal transaction ID).
 * These are external identifiers provided by payment gateways, not generated by our system.
 *
 * Examples:
 * - Stripe: "ch_1J4Z5Z2eZvKYlo2C8Z5Z5Z5Z"
 * - PayPal: "9HP05742RH8748327"
 *
 * Business Rules:
 * - Must not be empty
 * - Preserves original format from gateway
 * - Case-sensitive
 */
final readonly class TransactionId implements \Stringable
{
    private function __construct(private string $value)
    {
        if ('' === trim($value)) {
            throw new \InvalidArgumentException('TransactionId cannot be empty');
        }

        // Validate reasonable length (most gateways use 20-50 characters)
        if (strlen($value) > 255) {
            throw new \InvalidArgumentException(sprintf('TransactionId too long: "%s". Maximum 255 characters', $value));
        }
    }

    /**
     * Create TransactionId from a gateway transaction identifier string.
     */
    public static function fromString(string $value): self
    {
        return new self($value);
    }

    /**
     * Get the TransactionId as a string.
     */
    public function toString(): string
    {
        return $this->value;
    }

    /**
     * Check equality with another TransactionId.
     */
    public function equals(TransactionId $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
