<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260306112342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('COMMENT ON COLUMN bundle_items.bundle_product_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.product_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.quantity IS \'\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.price_amount IS \'\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.price_currency IS \'\'');
        $this->addSql('COMMENT ON COLUMN carts.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN carts.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN carts.abandonment_email_sent IS \'\'');
        $this->addSql('COMMENT ON COLUMN catalog_categories.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN catalog_categories.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.subscription_trial_end IS \'\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.downloadable_expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.bundle_discount_percentage IS \'\'');
        $this->addSql('ALTER INDEX idx_consent_history_tenant RENAME TO IDX_8C2A40779033212A');
        $this->addSql('ALTER INDEX idx_consent_history_customer RENAME TO IDX_8C2A40779395C3F3');
        $this->addSql('ALTER INDEX idx_consent_history_consent_type RENAME TO IDX_8C2A407725DDD725');
        $this->addSql('ALTER INDEX idx_consent_history_created_at RENAME TO IDX_8C2A40778B8E8428');
        $this->addSql('COMMENT ON COLUMN consents.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN consents.tenant_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN consents.customer_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN consents.purpose IS \'\'');
        $this->addSql('COMMENT ON COLUMN consents.granted_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN consents.withdrawn_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN consents.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN consents.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.street2 IS \'\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.type IS \'\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.is_default_shipping IS \'\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.is_default_billing IS \'\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.is_deleted IS \'\'');
        $this->addSql('CREATE INDEX IDX_C4378D0C8CDE5729 ON customer_addresses (type)');
        $this->addSql('CREATE INDEX IDX_C4378D0C75F24C7 ON customer_addresses (is_default_shipping)');
        $this->addSql('CREATE INDEX IDX_C4378D0CC03A3B51 ON customer_addresses (is_default_billing)');
        $this->addSql('CREATE INDEX IDX_C4378D0CFD07C8FB ON customer_addresses (is_deleted)');
        $this->addSql('ALTER INDEX idx_customer_addresses_customer RENAME TO IDX_C4378D0C9395C3F3');
        $this->addSql('ALTER INDEX idx_customer_addresses_tenant RENAME TO IDX_C4378D0C9033212A');
        $this->addSql('COMMENT ON COLUMN customers.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_order_updates IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_shipping_updates IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_promotional_offers IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_price_drop_alerts IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_back_in_stock_alerts IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_security_alerts IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_newsletter_weekly IS \'\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_prefer_sms IS \'\'');
        $this->addSql('ALTER INDEX idx_customers_email_bi RENAME TO IDX_62534E214FF5C1E2');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.tenant_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.customer_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.request_type IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.status IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.submitted_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.completed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.deadline IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.scheduled_for IS \'\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.confirmed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.completed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.created_at IS \'\'');
        $this->addSql('ALTER INDEX idx_deletion_requests_tenant_id RENAME TO IDX_F5574D879033212A');
        $this->addSql('ALTER INDEX idx_deletion_requests_customer_id RENAME TO IDX_F5574D879395C3F3');
        $this->addSql('ALTER INDEX idx_deletion_requests_status RENAME TO IDX_F5574D877B00651C');
        $this->addSql('ALTER INDEX idx_deletion_requests_scheduled_for RENAME TO IDX_F5574D8794A7B9CE');
        $this->addSql('ALTER TABLE ext_translations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ext_translations ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN invoice_lines.position IS \'\'');
        $this->addSql('CREATE INDEX idx_invoice_lines_tenant_id ON invoice_lines (tenant_id)');
        $this->addSql('COMMENT ON COLUMN invoices.status IS \'\'');
        $this->addSql('COMMENT ON COLUMN invoices.tax_breakdown IS \'\'');
        $this->addSql('COMMENT ON COLUMN invoices.is_reverse_charge IS \'\'');
        $this->addSql('COMMENT ON COLUMN invoices.credited_invoice_id IS \'\'');
        $this->addSql('ALTER INDEX uq_loyalty_programs_tenant RENAME TO unique_program_per_tenant');
        $this->addSql('ALTER INDEX idx_loyalty_tiers_program RENAME TO IDX_BCB1DBD93EB8070A');
        $this->addSql('ALTER INDEX idx_loyalty_tiers_threshold RENAME TO idx_loyalty_tiers_program_threshold');
        $this->addSql('COMMENT ON COLUMN notifications.sent_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notifications.failed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN notifications.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN orders.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN orders.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_orders_tenant_customer_bi RENAME TO idx_orders_tenant_customer');
        $this->addSql('ALTER INDEX idx_orders_customer_created_bi RENAME TO idx_orders_customer_created');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.user_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.used_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.created_at IS \'\'');
        $this->addSql('ALTER INDEX idx_prt_token RENAME TO idx_token');
        $this->addSql('ALTER INDEX idx_prt_user_id RENAME TO idx_user_id');
        $this->addSql('ALTER INDEX idx_prt_expires_at RENAME TO idx_expires_at');
        $this->addSql('COMMENT ON COLUMN price_history.changed_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN price_history.source IS \'\'');
        $this->addSql('COMMENT ON COLUMN price_lists.valid_from IS \'\'');
        $this->addSql('COMMENT ON COLUMN price_lists.valid_to IS \'\'');
        $this->addSql('COMMENT ON COLUMN price_lists.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN price_lists.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN price_lists.segment_rules IS \'\'');
        $this->addSql('COMMENT ON COLUMN promotions.valid_from IS \'\'');
        $this->addSql('COMMENT ON COLUMN promotions.valid_to IS \'\'');
        $this->addSql('COMMENT ON COLUMN promotions.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN promotions.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN promotions.target_segments IS \'\'');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN return_requests.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN return_requests.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN stock_items.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN stock_items.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN stock_reservations.reserved_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN stock_reservations.expires_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN stock_reservations.released_at IS \'\'');
        $this->addSql('ALTER TABLE tax_rules ALTER is_reverse_charge DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN tax_rules.category IS \'\'');
        $this->addSql('COMMENT ON COLUMN tax_rules.rate IS \'\'');
        $this->addSql('COMMENT ON COLUMN tax_rules.priority IS \'\'');
        $this->addSql('COMMENT ON COLUMN tenants.created_at IS \'\'');
        $this->addSql('ALTER TABLE test_translatable ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE test_translatable ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN users.mfa_enabled_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN warehouses.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN warehouses.updated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN wishlists.items IS \'\'');
        $this->addSql('COMMENT ON COLUMN wishlists.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN wishlists.updated_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('COMMENT ON COLUMN bundle_items.bundle_product_id IS \'Reference to the bundle product (type=bundle)\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.product_id IS \'Reference to the product included in the bundle\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.quantity IS \'Quantity of this product in the bundle (min: 1)\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.price_amount IS \'Price captured at bundle creation (cents, immutable)\'');
        $this->addSql('COMMENT ON COLUMN bundle_items.price_currency IS \'Currency code (ISO 4217)\'');
        $this->addSql('COMMENT ON COLUMN carts.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN carts.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN carts.abandonment_email_sent IS \'Whether abandonment recovery email has been sent for this cart\'');
        $this->addSql('COMMENT ON COLUMN catalog_categories.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN catalog_categories.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.bundle_discount_percentage IS \'Bundle discount percentage (0-50%, NULL for non-bundle products)\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.subscription_trial_end IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.downloadable_expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN catalog_products.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_8c2a40779395c3f3 RENAME TO idx_consent_history_customer');
        $this->addSql('ALTER INDEX idx_8c2a40778b8e8428 RENAME TO idx_consent_history_created_at');
        $this->addSql('ALTER INDEX idx_8c2a407725ddd725 RENAME TO idx_consent_history_consent_type');
        $this->addSql('ALTER INDEX idx_8c2a40779033212a RENAME TO idx_consent_history_tenant');
        $this->addSql('COMMENT ON COLUMN consents.id IS \'(DC2Type:consent_id)\'');
        $this->addSql('COMMENT ON COLUMN consents.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('COMMENT ON COLUMN consents.customer_id IS \'(DC2Type:customer_id)\'');
        $this->addSql('COMMENT ON COLUMN consents.purpose IS \'(DC2Type:consent_purpose)\'');
        $this->addSql('COMMENT ON COLUMN consents.granted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN consents.withdrawn_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN consents.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN consents.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('DROP INDEX IDX_C4378D0C8CDE5729');
        $this->addSql('DROP INDEX IDX_C4378D0C75F24C7');
        $this->addSql('DROP INDEX IDX_C4378D0CC03A3B51');
        $this->addSql('DROP INDEX IDX_C4378D0CFD07C8FB');
        $this->addSql('COMMENT ON COLUMN customer_addresses.street2 IS \'Optional additional street address line (apartment, suite, etc.)\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.type IS \'Address type: shipping, billing, or both\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.is_default_shipping IS \'Is this the default shipping address for the customer\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.is_default_billing IS \'Is this the default billing address for the customer\'');
        $this->addSql('COMMENT ON COLUMN customer_addresses.is_deleted IS \'Soft delete flag - deleted addresses are hidden but retained for historical records\'');
        $this->addSql('ALTER INDEX idx_c4378d0c9395c3f3 RENAME TO idx_customer_addresses_customer');
        $this->addSql('ALTER INDEX idx_c4378d0c9033212a RENAME TO idx_customer_addresses_tenant');
        $this->addSql('COMMENT ON COLUMN customers.notif_order_updates IS \'Order updates notification (cannot be disabled - transactional)\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_shipping_updates IS \'Shipping updates notification\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_promotional_offers IS \'Promotional offers notification (requires marketing consent)\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_price_drop_alerts IS \'Price drop alerts notification\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_back_in_stock_alerts IS \'Back in stock alerts notification\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_security_alerts IS \'Security alerts notification (cannot be disabled - legal requirement)\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_newsletter_weekly IS \'Weekly newsletter subscription\'');
        $this->addSql('COMMENT ON COLUMN customers.notif_prefer_sms IS \'Prefer SMS over email (requires phone number)\'');
        $this->addSql('COMMENT ON COLUMN customers.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN customers.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_62534e214ff5c1e2 RENAME TO idx_customers_email_bi');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.id IS \'(DC2Type:data_subject_request_id)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.tenant_id IS \'(DC2Type:tenant_id)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.customer_id IS \'(DC2Type:customer_id)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.request_type IS \'(DC2Type:request_type)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.status IS \'(DC2Type:request_status)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.submitted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.deadline IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN data_subject_requests.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.scheduled_for IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.confirmed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN deletion_requests.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_f5574d879033212a RENAME TO idx_deletion_requests_tenant_id');
        $this->addSql('ALTER INDEX idx_f5574d879395c3f3 RENAME TO idx_deletion_requests_customer_id');
        $this->addSql('ALTER INDEX idx_f5574d877b00651c RENAME TO idx_deletion_requests_status');
        $this->addSql('ALTER INDEX idx_f5574d8794a7b9ce RENAME TO idx_deletion_requests_scheduled_for');
        $this->addSql('ALTER TABLE ext_translations ALTER id SET DEFAULT nextval(\'ext_translations_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE ext_translations ALTER id DROP IDENTITY');
        $this->addSql('DROP INDEX idx_invoice_lines_tenant_id');
        $this->addSql('COMMENT ON COLUMN invoice_lines."position" IS \'Display order position (0-based)\'');
        $this->addSql('COMMENT ON COLUMN invoices.status IS \'Invoice status: draft, issued, paid, partially_paid, overdue, cancelled, credited\'');
        $this->addSql('COMMENT ON COLUMN invoices.tax_breakdown IS \'JSONB object with tax amounts per rate (e.g., {"standard_20": 2000, "reduced_10": 500})\'');
        $this->addSql('COMMENT ON COLUMN invoices.is_reverse_charge IS \'True for B2B EU reverse charge mechanism (no VAT charged)\'');
        $this->addSql('COMMENT ON COLUMN invoices.credited_invoice_id IS \'Reference to original invoice if this is a credit note\'');
        $this->addSql('ALTER INDEX unique_program_per_tenant RENAME TO uq_loyalty_programs_tenant');
        $this->addSql('ALTER INDEX idx_loyalty_tiers_program_threshold RENAME TO idx_loyalty_tiers_threshold');
        $this->addSql('ALTER INDEX idx_bcb1dbd93eb8070a RENAME TO idx_loyalty_tiers_program');
        $this->addSql('COMMENT ON COLUMN notifications.sent_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.failed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifications.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN orders.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN orders.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_orders_customer_created RENAME TO idx_orders_customer_created_bi');
        $this->addSql('ALTER INDEX idx_orders_tenant_customer RENAME TO idx_orders_tenant_customer_bi');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.used_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_tokens.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_expires_at RENAME TO idx_prt_expires_at');
        $this->addSql('ALTER INDEX idx_user_id RENAME TO idx_prt_user_id');
        $this->addSql('ALTER INDEX idx_token RENAME TO idx_prt_token');
        $this->addSql('COMMENT ON COLUMN price_history.changed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN price_history.source IS \'manual, import, promotion, flash_sale\'');
        $this->addSql('COMMENT ON COLUMN price_lists.segment_rules IS \'Segment-based pricing rules (higher priority than general rules)\'');
        $this->addSql('COMMENT ON COLUMN price_lists.valid_from IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN price_lists.valid_to IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN price_lists.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN price_lists.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN promotions.target_segments IS \'Customer segments this promotion applies to (empty = all segments)\'');
        $this->addSql('COMMENT ON COLUMN promotions.valid_from IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN promotions.valid_to IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN promotions.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN promotions.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN return_requests.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN return_requests.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN stock_items.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN stock_items.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN stock_reservations.reserved_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN stock_reservations.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN stock_reservations.released_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE tax_rules ALTER is_reverse_charge SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN tax_rules.category IS \'Tax category: standard, reduced, zero, exempt, reverse_charge\'');
        $this->addSql('COMMENT ON COLUMN tax_rules.rate IS \'Tax rate percentage (0.00-100.00)\'');
        $this->addSql('COMMENT ON COLUMN tax_rules.priority IS \'Higher priority rules override lower priority when multiple rules match\'');
        $this->addSql('COMMENT ON COLUMN tenants.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE test_translatable ALTER id SET DEFAULT nextval(\'test_translatable_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE test_translatable ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.mfa_enabled_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN warehouses.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN warehouses.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wishlists.items IS \'(DC2Type:json)\'');
        $this->addSql('COMMENT ON COLUMN wishlists.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wishlists.updated_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
