apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    url: http://tempo:3200
    isDefault: true
    jsonData:
      nodeGraph:
        enabled: true

  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
