<?php

declare(strict_types=1);

namespace App\Tests\Contract\Order\Returns;

use App\Returns\Domain\Event\ReturnRequestCompleted;
use App\Returns\Domain\Event\ReturnRequestCreated;
use App\Returns\Domain\ValueObject\ReturnRequestId;
use App\Shared\Domain\ValueObject\TenantId;
use PHPUnit\Framework\Attributes\CoversNothing;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * Contract tests for the Order <-> Returns boundary.
 *
 * Verifies that Returns events maintain the contract expected by
 * Order and other consuming contexts (Notifications, Inventory).
 *
 * Producer: Returns (ReturnRequestCreated, ReturnRequestCompleted)
 * Consumer: Order, Notifications, Inventory (future)
 */
#[CoversNothing]
#[Group('contract')]
final class OrderReturnsContractTest extends TestCase
{
    private const TENANT_ID = '00000000-0000-4000-8000-000000000001';

    // -----------------------------------------------------------------------
    // ReturnRequestCreated — produced by Returns
    // -----------------------------------------------------------------------

    #[Test]
    public function returnRequestCreatedHasRequiredFields(): void
    {
        $event = ReturnRequestCreated::create(
            returnRequestId: ReturnRequestId::generate(),
            tenantId: TenantId::fromString(self::TENANT_ID),
            orderId: '550e8400-e29b-41d4-a716-446655440000',
            reason: 'Product defective',
        );

        self::assertInstanceOf(ReturnRequestId::class, $event->returnRequestId);
        self::assertInstanceOf(TenantId::class, $event->tenantId);
        self::assertIsString($event->orderId);
        self::assertNotEmpty($event->orderId);
        self::assertIsString($event->reason);
        self::assertNotEmpty($event->reason);
        self::assertInstanceOf(\DateTimeImmutable::class, $event->occurredOn);
    }

    #[Test]
    public function returnRequestCreatedOrderIdIsStringUuid(): void
    {
        $orderId = '550e8400-e29b-41d4-a716-446655440000';
        $event = ReturnRequestCreated::create(
            returnRequestId: ReturnRequestId::generate(),
            tenantId: TenantId::fromString(self::TENANT_ID),
            orderId: $orderId,
            reason: 'Wrong item received',
        );

        // Contract: orderId is a string UUID, not an OrderId value object
        // Consumer must convert if needed
        self::assertSame($orderId, $event->orderId);
        self::assertMatchesRegularExpression(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/',
            $event->orderId
        );
    }

    #[Test]
    public function returnRequestCreatedOccurredOnIsAutoGenerated(): void
    {
        $before = new \DateTimeImmutable();
        $event = ReturnRequestCreated::create(
            returnRequestId: ReturnRequestId::generate(),
            tenantId: TenantId::fromString(self::TENANT_ID),
            orderId: '550e8400-e29b-41d4-a716-446655440000',
            reason: 'Changed my mind',
        );
        $after = new \DateTimeImmutable();

        self::assertGreaterThanOrEqual($before, $event->occurredOn);
        self::assertLessThanOrEqual($after, $event->occurredOn);
    }

    // -----------------------------------------------------------------------
    // ReturnRequestCompleted — produced by Returns, consumed by Notifications
    // -----------------------------------------------------------------------

    #[Test]
    public function returnRequestCompletedHasRequiredFields(): void
    {
        $event = ReturnRequestCompleted::create(
            returnRequestId: ReturnRequestId::generate(),
            tenantId: TenantId::fromString(self::TENANT_ID),
            refundAmount: 4999,
            refundCurrency: 'USD',
        );

        self::assertInstanceOf(ReturnRequestId::class, $event->returnRequestId);
        self::assertInstanceOf(TenantId::class, $event->tenantId);
        self::assertIsInt($event->refundAmount);
        self::assertGreaterThanOrEqual(0, $event->refundAmount);
        self::assertIsString($event->refundCurrency);
        self::assertNotEmpty($event->refundCurrency);
        self::assertInstanceOf(\DateTimeImmutable::class, $event->occurredOn);
    }

    #[Test]
    public function returnRequestCompletedRefundAmountIsInCents(): void
    {
        $event = ReturnRequestCompleted::create(
            returnRequestId: ReturnRequestId::generate(),
            tenantId: TenantId::fromString(self::TENANT_ID),
            refundAmount: 2500,
            refundCurrency: 'EUR',
        );

        // Contract: refundAmount is in minor currency units (cents)
        self::assertSame(2500, $event->refundAmount);
        self::assertSame('EUR', $event->refundCurrency);
    }

    #[Test]
    public function returnRequestCompletedCurrencyIsIso4217Code(): void
    {
        $event = ReturnRequestCompleted::create(
            returnRequestId: ReturnRequestId::generate(),
            tenantId: TenantId::fromString(self::TENANT_ID),
            refundAmount: 1000,
            refundCurrency: 'GBP',
        );

        self::assertMatchesRegularExpression('/^[A-Z]{3}$/', $event->refundCurrency);
    }

    // -----------------------------------------------------------------------
    // ReturnRequestId value object contract
    // -----------------------------------------------------------------------

    #[Test]
    public function returnRequestIdSerializesConsistently(): void
    {
        $id = ReturnRequestId::generate();
        $serialized = $id->toString();
        $deserialized = ReturnRequestId::fromString($serialized);

        self::assertSame($serialized, $deserialized->toString());
    }
}
