<?php

declare(strict_types=1);

namespace App\Payment\Presentation\Api\Processor;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Payment\Application\Command\AuthorizePayment;
use App\Payment\Domain\ValueObject\PaymentId;
use App\Payment\Infrastructure\Persistence\Doctrine\Entity\PaymentEntity;
use App\Shared\Domain\ValueObject\TenantId;
use Symfony\Component\Messenger\MessageBusInterface;

final readonly class AuthorizePaymentProcessor implements ProcessorInterface
{
    public function __construct(
        private MessageBusInterface $commandBus
    ) {
    }

    /**
     * @param PaymentEntity $data
     */
    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): PaymentEntity
    {
        // Note: The gateway transaction ID is generated by the payment gateway during authorization
        // The handler will call the gateway and retrieve the transaction ID
        $command = new AuthorizePayment(
            id: PaymentId::fromString($data->getId()),
            tenantId: TenantId::fromString($data->getTenantId())
        );

        $this->commandBus->dispatch($command);

        return $data;
    }
}
